---
- hosts: all
  become: true
  vars_files:
    - vars/main.yml
  roles:
    - { role: common, tags: [ 'common' ] }
    - geerlingguy.clamav
    - { role: geerlingguy.mysql, tags: [ 'mysql' ] }
    - geerlingguy.java
    - andrewrothstein.python
    - geerlingguy.php
    - geerlingguy.php-mysql
    - geerlingguy.apache
    - geerlingguy.solr
    - { role: orb, tags: [ 'orb', 'app' ] }
