---
- hosts: all
  become: true
  roles:
    - { role: common, tags: [ 'common' ] }
    - geerlingguy.clamav
    - geerlingguy.mysql
    - geerlingguy.java
    - andrewrothstein.python
    - geerlingguy.php
    - geerlingguy.php-mysql
    - geerlingguy.apache
    - geerlingguy.solr
    - { role: orb, tags: [ 'orb', 'app' ] }
