---
# file: mod_wsgi/tasks/debug.yml
#
# debug tasks.
#

- debug:
    var="{{ item }}"
  when: "{{ item }} is defined"
  with_items:
    - mod_wsgi_dir_scripts
    - mod_wsgi_installation
    - mod_wsgi_use_httpd
