---
# file: mod_wsgi/meta/main.yml
#
# meta file
#
galaxy_info:
  author: Pedro Salgado.
  description: Ansible role to install and setup mod_wsgi.
  company: ansiblebit.org
  license: BSD
  min_ansible_version: 2.0
  platforms:
    - name: Debian
      versions:
        - jessie
        - wheezy
    - name: Ubuntu
      versions:
        - xenial
        - vivid
        - trusty
        - precise
  galaxy_tags:
    - apache
    - debian
    - mod_wsgi
    - ubuntu
    - web

dependencies:
  - role: ansiblebit.httpd
    when: mod_wsgi_use_httpd is defined and
          mod_wsgi_use_httpd
    tags: [ apache, httpd ]
