---
# file: mod_wsgi/tasks/package/validation.yml
#
# package validation tasks.
#

- name: ensure mandatory variables are set
  fail:
    msg="{{ item }} is a mandatory variable"
  when: "{{ item }} is not defined"
  with_items: []
