---
- name: Ensure git is installed.
  apt:
    name: "git"
    state: installed

# Required for installing Python-MySQL
- name: Ensure Mysql client installed.
  apt:
    name: "libmysqlclient-dev"
    state: installed

- name: Ensure Python headers installed.
  apt:
    name: "python-dev"
    state: installed

- name: Include all .json and .jsn files in vars/all and all nested directories (2.3)
  include_vars:
    dir: 'vars/local'
    extensions:
        - json
        - yml
        - yaml
